### ISSUE TITLE
https://meet.jit.si/ no longer works on Waterfox

### ISSUE THREAD

**Issue by rorya** [BrowserWorks/waterfox#1176]
I have noticed recently that the free screen sharing site, https://meet.jit.si/ no longer works on Waterfox (56.2.11 in my case). I have verified that it does work on FX 69 just fine. On WF it it just showing a dark gray screen.

**Comment by rorya** [comment]
It may be an issue with jit.si not testing on the detected browser, Firefox 56, it says.

I see this error in the console:

TypeError: r.map is not a function[Learn More]  functions.js:27:28
	<anonymous> functions.js:27:28
	<anonymous> functions.js:20
	n bootstrap:19
	<anonymous> reducer.js:27:15
	n bootstrap:19
	<anonymous> actions.js:20:66
	n bootstrap:19
	<anonymous> index.js:67:12
	n bootstrap:19
	<anonymous> actions.js:17:8
	n bootstrap:19
	<anonymous> AuthHandler.js:1
	<anonymous> AuthHandler.js:1
	n bootstrap:19
	<anonymous> connection.js:1
	<anonymous> connection.js:1
	n bootstrap:19
	<anonymous> conference.js:1
	<anonymous> conference.js:1
	n bootstrap:19
	<anonymous> index.js:109
	n bootstrap:19
	<anonymous> bootstrap:83
	<anonymous> https://web-cdn.jitsi.net/meetjitsi_3613.341/libs/app.bundle.min.js:1:2

**Comment by hawkeye116477** [comment]
That's already fixed on https://github.com/MrAlex94/Waterfox/pull/1164, but unfortunately not green-lighted yet by @MrAlex94.

**Comment by pjpreilly** [comment]
The traffic lights still working?

**Comment by MrAlex94** [comment]
Has been pulled in now :-)

**Comment by pjpreilly** [comment]
Do you want a test run by me before release?

**Comment by pjpreilly** [comment]
... for the Lion/ML crash issue?

**Comment by timur-g** [comment]
I had a crash opening Jitsi in Windows 7 with WF Classic 2020.09 64-bit for example https://jitsi.documentfoundation.org/ilmaritriages. I thought it would be this issue. 
Today I upgraded to WF Classic 2020.10 and I still have a crash of the Jitsi tab, after I allow microphone/camera (I don't remember it). No crash if skip to allow microphone. Microphone mentioned in #1513 for Windows (but it's closed!) and #1446 for Linux. 
I don't have Visual Studio JIT Debugger. I just see "an unhandled win32 exception occured in waterfox [3600]"
Looks like a known issue of allowing microphone. I can attach Developer web console output.

**Comment by timur-g** [comment]
This is closed, but I still have a tab crash on Jitsi when allowing microphone in WF Classic 2021.04 64-bit .
