### ISSUE TITLE
OneTab no longer working

### ISSUE THREAD

**Issue by FanofWF** [BrowserWorks/waterfox#263]
I found OneTab a really useful add-on.  But since the last Waterfox update (55.2.2 64-bit) it stopped working.  When I click on the button, nothing happens.  
Of the manual functions, "Send only this tab to OneTab" gives the impression it works.  But actually the tab simply disappears.  It does not go to the OneTab page, and it is removed from the displayed tabs.  So the worst of all possible outcomes.
I tried uninstalling and reinstalling the add-on.  No change.

**Comment by criztovyl** [comment]
Could you try to open the browser console or run from console and see if there are any errors if you send the tabs to onetab?

Browser Console is CTRL + ALT + J, or use Hamburger-Menu &rarr; Developer &rarr; Browser Console.

**Comment by MrAlex94** [comment]
As @criztovyl said, would be great help.

**Comment by FanofWF** [comment]
Is this what you were looking for?
W8 moz-extension://7f5b31e6-a038-49de-b38a-55ad62d41296/ext-onetab-concatenated-sources-background.js:5:56291
	_8 moz-extension://7f5b31e6-a038-49de-b38a-55ad62d41296/ext-onetab-concatenated-sources-background.js:5:56365
	s8 moz-extension://7f5b31e6-a038-49de-b38a-55ad62d41296/ext-onetab-concatenated-sources-background.js:5:58082
	parse moz-extension://7f5b31e6-a038-49de-b38a-55ad62d41296/ext-onetab-concatenated-sources-background.js:5:58256
	OX/< moz-extension://7f5b31e6-a038-49de-b38a-55ad62d41296/ext-onetab-concatenated-sources-background.js:5:47336
	S.prototype.LW/< moz-extension://7f5b31e6-a038-49de-b38a-55ad62d41296/ext-onetab-concatenated-sources-background.js:5:23241
	runSafeSyncWithoutClone resource://gre/modules/ExtensionUtils.jsm:52:14
	runSafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:176:38
	runSafeWithoutClone self-hosted:945:17
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:355:13

**Comment by criztovyl** [comment]
This looks like a stack trace, but the exception is missing. Maybe a screenshot would be better :)

(try to use ` ``` ` at line before and after the block of log next time, formats it as code and makes it slightly better readable :) )

**Comment by FanofWF** [comment]
I'll do that.  In the meantime, here is another block of text from the Browser Consol that I've cut and pasted:

The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.  onetab.html
h8.charAt is not a function ext-onetab-concatenated-sources-background.js:5
GET 
https://www.google.com/s2/favicons [HTTP/2.0 400 Bad Request 463ms]
h8.charAt is not a function  ext-onetab-concatenated-sources-background.js:5

**Comment by FanofWF** [comment]
```
h8.charAt is not a function  ext-onetab-concatenated-sources-background.js:5

```

**Comment by criztovyl** [comment]
What version of OneTab are you using?

Try to downgrade to 1.23 or 1.17 and see if the error persists.
Also see [the addon's amo page](https://addons.mozilla.org/de/firefox/addon/onetab/), there are some compatibility notes.

**Comment by FanofWF** [comment]
I am using 1.23 (on Waterfox 55.2.2 64 bit).
Full disclosure: OneTab was also not working on Firefox 56.0 but is now working fine on 57.0

How do I downgrade to OneTab 1.17?

**Comment by criztovyl** [comment]
Try to install from there: https://addons.mozilla.org/de/firefox/addon/onetab/versions/1.17.0

**Comment by FanofWF** [comment]
Thanks!  That's solved my problem.  I appreciate you patiently stepping me through it.

**Comment by criztovyl** [comment]
Glad I could help.
You're welcome.

**Comment by DARKFiB3R** [comment]
1.17 is no longer available from Mozilla. Does anybody have a copy please? Thanks.

Edit: Found it. http://ge.tt/3aEvBet2

**Comment by grahamperrin** [comment]
caa:addon/onetab/versions?page=1#version-1.17.0
