### ISSUE TITLE
Error building Waterfox from master

### ISSUE THREAD

**Issue by laniakea64** [BrowserWorks/waterfox#473]
Xubuntu 16.04 64-bit

Attempting to build Waterfox from https://github.com/MrAlex94/Waterfox/commit/2e133a1c8aaaeda4c6eaff8142b8a6a9348952ae fails with this error -
```
error: doc comment not used by rustdoc
   --> /media/gecko/waterfox/Waterfox/servo/components/style/values/specified/image.rs:689:17
    |
689 |                 /// `to` keyword is mandatory in modern syntax.
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: lint level defined here
   --> /media/gecko/waterfox/Waterfox/servo/components/style/lib.rs:26:9
    |
26  | #![deny(warnings)]
    |         ^^^^^^^^
    = note: #[deny(unused_doc_comment)] implied by #[deny(warnings)]

error: doc comment not used by rustdoc
   --> /media/gecko/waterfox/Waterfox/servo/components/style/values/specified/image.rs:695:17
    |
695 |                 /// There is no `to` keyword in webkit prefixed syntax. If it's consumed,
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: doc comment not used by rustdoc
    --> /media/gecko/waterfox/Waterfox/objdir/toolkit/library/x86_64-unknown-linux-gnu/release/build/style-9c2513b3ace15841/out/gecko_properties.rs:9131:9
     |
9131 |         /// XXXManishearth this should also handle text zoom
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0106]: missing lifetime specifier
   --> /media/gecko/waterfox/Waterfox/objdir/toolkit/library/x86_64-unknown-linux-gnu/release/build/style-9c2513b3ace15841/out/gecko/bindings.rs:569:9
    |
569 |      -> RawGeckoNodeBorrowedOrNull;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected lifetime parameter
    |
    = help: this function's return type contains a borrowed value with an elided lifetime, but the lifetime cannot be derived from the arguments
    = help: consider giving it an explicit bounded or 'static lifetime

error[E0106]: missing lifetime specifier
   --> /media/gecko/waterfox/Waterfox/objdir/toolkit/library/x86_64-unknown-linux-gnu/release/build/style-9c2513b3ace15841/out/gecko/bindings.rs:841:9
    |
841 |      -> RawServoAnimationValueBorrowedOrNull;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected lifetime parameter
    |
    = help: this function's return type contains a borrowed value with an elided lifetime, but the lifetime cannot be derived from the arguments
    = help: consider giving it an explicit bounded or 'static lifetime

error: aborting due to 5 previous errors

error: Could not compile `style`.

To learn more, run the command again with --verbose.
/media/gecko/waterfox/Waterfox/config/rules.mk:986: recipe for target 'force-cargo-library-build' failed
make[6]: *** [force-cargo-library-build] Error 101
make[6]: Leaving directory '/media/gecko/waterfox/Waterfox/objdir/toolkit/library/rust'
/media/gecko/waterfox/Waterfox/config/recurse.mk:73: recipe for target 'toolkit/library/rust/target' failed
make[5]: *** [toolkit/library/rust/target] Error 2
make[5]: *** Waiting for unfinished jobs....
```

**Comment by grahamperrin** [comment]
Via <https://www.google.co.uk/search?q=Servo+%22to%60+keyword+is+mandatory+in+modern+syntax.%22>: 

- Mozilla bug [1423684 - Can't build old revisions due to Rust errors](https://bugzilla.mozilla.org/show_bug.cgi?id=1423684)

– with a mention of Stylo in the first response. Any help? Or OT?

**Comment by MrAlex94** [comment]
You need to build with Rust 1.17.0 specifically. 

rustup toolchain install 1.17.0

Then use rustup default to set this version.

**Comment by laniakea64** [comment]
It works with Rust 1.17.0!  Thanks for the replies.

Would it be possible to make the configure stage error out on incompatible Rust version?

**Comment by jbeich** [comment]
Or backport mozilla/gecko-dev@95a1778f4ef0 ([example](https://github.com/freebsd/freebsd-ports/blob/9fdee2ead87a/www/waterfox/files/patch-bug1434619)).
