### ISSUE TITLE
"TypeError: 'stopPropagation' called on an object that does not implement Event." when using vimperator

### ISSUE THREAD

**Issue by sebeka** [BrowserWorks/waterfox#756]
Dear Waterfox team,

the only reason I tried to switch from firefox to waterfox is the vimperator extension.
Unfortunately, waterfox 56.2.3 is not working with enabled vimperator extension 3.16:

In warterfox I get in the bottom line: (all the time)
 'stopPropagation' called on an object that does not implement Event.

The bottom line is also used by vimperator, so that there are multiple lines over each other.
It's not possible to read anything.

I was also not able to enter a password on a login form (that one from github), since it seams to type in the bottom line.

Would be nice if you can fix this,

Thanks,

Sebastian

**Comment by grahamperrin** [comment]
> … in the bottom line: (all the time)
> `'stopPropagation' called on an object that does not implement Event.`

I don't see that with Waterfox 56.2.3 on FreeBSD-CURRENT. 

Please subscribe to: 

- [TypeError: 'stopPropagation' called on an object that does not implement interface Event · Issue #582 · vimperator/vimperator-labs](https://github.com/vimperator/vimperator-labs/issues/582)
