### PR TITLE
Re-vendor the app_units crate to the latest version

### PR DESCRIPTION
**Pull request by vishwin**
This unbreaks the build with Rust 1.35. Error before re-vendoring:
```
   Compiling app_units v0.5.1
error[E0658]: use of unstable library feature 'clamp' (see issue #44095)
   --> /wrkdirs/usr/ports/www/waterfox/work/Waterfox-56.2.10/third_party/rust/app_units/src/app_unit.rs:192:22
    |
192 |         *self = self.clamp()
    |                      ^^^^^

error[E0061]: this function takes 2 parameters but 0 parameters were supplied
   --> /wrkdirs/usr/ports/www/waterfox/work/Waterfox-56.2.10/third_party/rust/app_units/src/app_unit.rs:192:22
    |
192 |         *self = self.clamp()
    |                      ^^^^^ expected 2 parameters

error[E0308]: mismatched types
   --> /wrkdirs/usr/ports/www/waterfox/work/Waterfox-56.2.10/third_party/rust/app_units/src/app_unit.rs:192:17
    |
192 |         *self = self.clamp()
    |                 ^^^^^^^^^^^^
    |                 |
    |                 expected struct `app_unit::Au`, found mutable reference
    |                 help: consider dereferencing the borrow: `*self.clamp()`
    |
    = note: expected type `app_unit::Au`
               found type `&mut app_unit::Au`

error: aborting due to 3 previous errors

Some errors occurred: E0061, E0308, E0658.
For more information about an error, try `rustc --explain E0061`.
error: Could not compile `app_units`.

To learn more, run the command again with --verbose.
gmake[4]: *** [/wrkdirs/usr/ports/www/waterfox/work/Waterfox-56.2.10/config/rules.mk:999: force-cargo-library-build] Error 101
```
No functional change intended.

### CODE REVIEW

**Comment by hawkeye116477** [comment]
Hmm, I have rust 1.35 and I don't have that error.
