### ISSUE TITLE
Random segfaults (archlinux)

### ISSUE THREAD

**Issue by HotelBellaMuerte** [BrowserWorks/waterfox#298]
BUILDS
GCC: 7.2.0

Clang: 5.0.0

https://p.teknik.io/cRHo7

**Comment by HotelBellaMuerte** [comment]
@hawkeye116477
@mralex94

**Comment by hawkeye116477** [comment]
@bn0785ac I built it on Manjaro Linux before I pushed new version to AUR and everything was ok.  Maybe you try to enable stylo and that's the problem, stylo should be disabled.

**Comment by jbeich** [comment]
> /home/senpai/bm/yaourt-tmp-senpai/aur-waterfox-kde/waterfox-git/src/Waterfox/obj-x86_64-pc-linux-gnu/dist/include/nsISupportsImpl.h:17:10: fatal error: 'prthread.h' file not found, err: true
> /home/senpai/bm/yaourt-tmp-senpai/aur-waterfox-kde/waterfox-git/src/Waterfox/obj-x86_64-pc-linux-gnu/dist/include/nsString.h:162:10: fatal error: 'plhash.h' file not found, err: true

Probably [bug 1341234](https://bugzilla.mozilla.org/show_bug.cgi?id=1341234). Stylo on Waterfox 56 may also fail to build with Rust 1.21+ ([example fix](https://github.com/freebsd/freebsd-ports/commit/b7ecbc06d9eb))

**Comment by grahamperrin** [comment]
With #332 closed today, a review of this issue 298 is timely. 

Can it be closed?
